### ISSUE TITLE
Errors after homebrew update

### ISSUE THREAD

**Issue by dahankzter** [pivotal/homebrew-tap#81]
Today I started getting these errors

```bash
Updated Homebrew from 92acdb5 to cd23c26.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/pivotal/homebrew-tap/gemfirexd.rb:6:in `<class:Gemfirexd>'
Please report this to the pivotal/tap tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/pivotal/homebrew-tap/gemfirexd.rb:6:in `<class:Gemfirexd>'
Please report this to the pivotal/tap tap!
```

**Comment by nebhale** [comment]
This was due to a change in Homebrew and was fixed in [these commits](https://github.com/pivotal/homebrew-tap/compare/fd41062ee63b8c4eb04de56b635090946be1d331...604193be6444901ebae105b7d6463244a09c2ced).  Ensure that your tap is up to date using `brew update` and see if you still have the same issue.

**Comment by dahankzter** [comment]
Work fine now thanks!
